name: Saludo usando variables y secretos
run-name: ¡Estoy aprendiendo a usar Variables y secretos!
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, $NOMBRE. Hoy es $DIA_DE_SEMANA!"
        env:
          NOMBRE: Carolina
  saludo-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo secreto
        run: echo "$SALUDO, ${{ vars.NOMBRE }}. Tu contraseña es ${{ secrets.CONTRASENA }}"
        env:
          NOMBRE: Carolina
